[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "complete_dbt_bootcamp_zero_to_hero.definitions"
code_location_name = "complete_dbt_bootcamp_zero_to_hero"

